# this file generated by tool/generate_ast.py
from abc import ABC

class Visitor(ABC):

    def visit_binary_expr(self, expr):
        raise NotImplementedError()

    def visit_grouping_expr(self, expr):
        raise NotImplementedError()

    def visit_literal_expr(self, expr):
        raise NotImplementedError()

    def visit_variable_expr(self, expr):
        raise NotImplementedError()

    def visit_unary_expr(self, expr):
        raise NotImplementedError()

    def visit_assign_expr(self, expr):
        raise NotImplementedError()

    def visit_logical_expr(self, expr):
        raise NotImplementedError()

    def visit_call_expr(self, expr):
        raise NotImplementedError()

class Expr(ABC):

    def accept(visitor: Visitor):
        pass

class Binary(Expr):

    def __init__(self, left, operator, right):
        self.left = left
        self.operator = operator
        self.right = right

    def accept(self, visitor: Visitor):
        return visitor.visit_binary_expr(self)


class Grouping(Expr):

    def __init__(self, expression):
        self.expression = expression

    def accept(self, visitor: Visitor):
        return visitor.visit_grouping_expr(self)


class Literal(Expr):

    def __init__(self, value):
        self.value = value

    def accept(self, visitor: Visitor):
        return visitor.visit_literal_expr(self)


class Variable(Expr):

    def __init__(self, name):
        self.name = name

    def accept(self, visitor: Visitor):
        return visitor.visit_variable_expr(self)


class Unary(Expr):

    def __init__(self, operator, right):
        self.operator = operator
        self.right = right

    def accept(self, visitor: Visitor):
        return visitor.visit_unary_expr(self)


class Assign(Expr):

    def __init__(self, name, value):
        self.name = name
        self.value = value

    def accept(self, visitor: Visitor):
        return visitor.visit_assign_expr(self)


class Logical(Expr):

    def __init__(self, left, operator, right):
        self.left = left
        self.operator = operator
        self.right = right

    def accept(self, visitor: Visitor):
        return visitor.visit_logical_expr(self)


class Call(Expr):

    def __init__(self, callee, paren, arguments):
        self.callee = callee
        self.paren = paren
        self.arguments = arguments

    def accept(self, visitor: Visitor):
        return visitor.visit_call_expr(self)


