# this file generated by tool/generate_ast.py
from abc import ABC

class Visitor(ABC):

    def visit_expression_stmt(self, expr):
        pass

    def visit_print_stmt(self, expr):
        pass

    def visit_var_stmt(self, expr):
        pass

    def visit_block_stmt(self, expr):
        pass

class Stmt(ABC):

    def accept(visitor: Visitor):
        pass

class Expression(Stmt):

    def __init__(self, expression):
        self.expression = expression

    def accept(self, visitor: Visitor):
        return visitor.visit_expression_stmt(self)


class Print(Stmt):

    def __init__(self, expression):
        self.expression = expression

    def accept(self, visitor: Visitor):
        return visitor.visit_print_stmt(self)


class Var(Stmt):

    def __init__(self, name, initializer):
        self.name = name
        self.initializer = initializer

    def accept(self, visitor: Visitor):
        return visitor.visit_var_stmt(self)


class Block(Stmt):

    def __init__(self, statements):
        self.statements = statements

    def accept(self, visitor: Visitor):
        return visitor.visit_block_stmt(self)


